name: PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:

  checklist-completed:
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-24.04
    steps:
      - uses: mheap/require-checklist-action@9c8100a52aa9726d4648e61aa92415f6c843c990 # v2
        with:
          # The checklist must _exist_ and be filled out.
          requireChecklist: true
